name: Deploy Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@master

          - uses: docker/login-action@v2
            with:
              username: gary50613
              password: ${{secrets.DOCKER_PASSWORD}}

          - uses: docker/setup-buildx-action@v2

          - uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: gary50613/jemalloc-alpine:latest
              cache-from: type=gha
              cache-to: type=gha,mode=max